Feature/#17760 ch9
redBorder/redborder-documentation pull request #23
Opened 2024-06-20 09:58 UTC by ljblancoredborder

2024-06-24 08:03 UTC, JPeraltaNic commented
@all-contributors please add @ljblancoredborder for content, translations

2024-06-26 08:01 UTC, JPeraltaNic requested changes
The brute force use case is using scripts from the CentOS 6 version, we need the use cases to be adapted to the Rocky 9 version of RedBorder

2024-06-26 08:57 UTC, JPeraltaNic requested changes

2024-06-26 08:57 UTC, JPeraltaNic commented on docs/guides/use_cases/images/ch30_img005_a.png
`rb_set_service.sh` is from CentOS 6

2024-06-26 10:46 UTC, ljblancoredborder commented on docs/guides/use_cases/images/ch30_img005_a.png
neither service or rbcli service is working with redborder-cep. I cannot update the images on current state.

2024-06-28 12:51 UTC, JPeraltaNic approved these changes

2024-06-28 12:52 UTC, merged