Feature #17758 Migrate chapter 7
redBorder/redborder-documentation pull request #27
Opened 2024-06-25 14:16 UTC by JPeraltaNic

## Related issue in RedMine

[Feature #17758](https://redmine.redborder.lan/issues/17758).

## Description / Motivation

You can now found information about general configuration for the platform, tools and how to use them (as explained in old manual)

## Detail

Some additions were made to match with the rocky 9 version features.

2024-06-26 15:58 UTC, ljblancoredborder requested changes

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +Si el usuario desea enviar sus registros a este servicio de Amazon, se deben completar los campos obligatorios.
... que son...
la frase queda muy cortante si no se explica el servicio o se dice cuáles son esos campos obligatorios

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +Es posible vincular Redborder con la API de Google Maps para obtener mejor información de ubicación.
... Añadir: Para ello es necesario disponer de una clave o identificador proporcionado por Google

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +OpenWeatherMap se utiliza en la pipeline de movilidad para enriquecer los datos de movilidad con información meteorológica. Este campo permite al usuario ingresar su clave API de OpenWeatherMap para
en el "módulo" de movilidad. Esta sección de la guía es para un usuario de la web no para un admin.

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +- **ASN**: la base de datos *GeoIP2* de IP anónima contiene datos sobre las direcciones IP de las redes que anónimo ha utilizado de diversas maneras.
podemos omitir a anónimo. No es una persona tan importante

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +Descargue todos los archivos del sitio web de Maxmind y descomprímalos. Solo es posible cargar archivos con formato .dat. Para esto, haga clic en **Seleccionar archivo**
no queda claro entonces por qué nosotros los subimos en formato .dat.gz

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +- **Geo IP**: Permite proteger la MAC del sensor, para esto se utiliza una clave codificada hexadecimal que se combina con una MAC falsa para obtener la MAC real de la misma.
Se está repitiendo lo mismo que antes. No entiendo por qué esta diferenciación

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +
Falta por mencionar el campo **enriquecimiento múltiple**

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +Con esta configuración, el usuario puede elegir qué información verá presentada en la barra lateral izquierda de la vista general, al entrar en la plataforma web. Todo lo que debe hacer el usuario es
"en la vista general de los dashboards", ya que por defecto se muestra el mapa

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +Con esta configuración, el usuario puede elegir qué información verá presentada en la barra lateral izquierda de la vista general, al entrar en la plataforma web. Todo lo que debe hacer el usuario es
en vez de removidos o agregados, mejor decir "que sean visibles"

2024-06-26 15:58 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.md
skipped review: check "es" traslation to mirror the changes for english traslation

2024-06-27 08:36 UTC, JPeraltaNic commented on docs/manager/platform_configurations/ch7_tools_and_admin.es.md
> +    Hay tres niveles para las alertas: información, advertencia y peligro. Cada nivel tiene su propio color para que las alertas se puedan diferenciar y todas se colocan por debajo de la barra de men
'Imagen' no lleva tilde, es una palabra grave que termina en 'n', sin embargo, su plural 'imágenes' sí que lleva tilde, debido a que esta última es una palabra esdrújula.

2024-06-27 08:43 UTC, JPeraltaNic commented on README.md
What do you mean?

2024-06-27 11:06 UTC, ljblancoredborder commented on README.md
i'm only seeing 
- mkdocs gh-deploy
+ mkdocs gh-deploy

2024-06-27 13:04 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +- **Largo mínimo de contraseña**: indica el número mínimo de caracteres que debe tener una contraseña para ser aceptada en la plataforma.
Tamaño mínimo mejor que Largo mínimo

2024-06-27 13:04 UTC, ljblancoredborder commented on docs/manager/platform_configurations/ch7_4_general_config.es.md
> +- **Nombre empresa**: nombre de la compañía que usa Redborder.
"Nombre de la empresa" mejor

2024-06-27 13:11 UTC, ljblancoredborder requested changes
general config .es changes

2024-06-27 13:22 UTC, manegron approved these changes

2024-06-27 13:23 UTC, merged